### ISSUE TITLE
filter_outliers fails with a strange message of a missing file

### ISSUE THREAD

**Issue by ralsallaq** [fhcrc/deenurp#64]
Hi,
I am having trouble executing filter_outliers.filter_sequences. It throws the following error:

Traceback (most recent call last):
  File "/hpcf/apps/python/install/2.7.13/lib/python2.7/site-packages/deenurp-0.0.0-py2.7.egg/deenurp/subcommands/filter_outliers.py", line 373, in filter_sequences
    sequence_file, prefix, cpu=threads or wrap.CMALIGN_THREADS)
  File "/hpcf/apps/python/install/2.7.13/lib/python2.7/site-packages/deenurp-0.0.0-py2.7.egg/deenurp/subcommands/filter_outliers.py", line 258, in distmat_cmalign
    taxa, distmat = outliers.fasttree_dists(a_fasta.name)
  File "/hpcf/apps/python/install/2.7.13/lib/python2.7/site-packages/deenurp-0.0.0-py2.7.egg/deenurp/outliers.py", line 52, in fasttree_dists
    proc = subprocess.Popen(cmd, stdout=stdout, stderr=devnull)
  File "/hpcf/apps/python/install/2.7.13/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/hpcf/apps/python/install/2.7.13/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
 
Thus, it seems it is complaining about a missing file which puzzles me. I have supplied both a sequence fasta file to save filtered sequences and a taxa fasta file for the unfiltered sequences with taxa info. Both the filtered and the unfiltered fasta files are initially identical (before filtering) and I verified that both o the files do exist before entering the filter_outliers.filter_sequences step. Not sure what file is missing that the OS via subprocess is complaining about. Your help is appreciated especially if you have a detailed example on how to use filter_outliers and fill_lonely. Thanks much in advance.

**Comment by ralsallaq** [comment]
I found the cause. I just forgot to load fasttree on the cluster! but the message does not indicate anything about fasttree. Thanks

**Comment by crosenth** [comment]
Agreed, adding this Issue as part of next release.  Thank you
